apiVersion: v1
kind: ServiceAccount
metadata:
  name: riotx-redis-migration
  namespace: redis-migration
  labels:
    app.kubernetes.io/name: riotx
    app.kubernetes.io/component: redis-cluster-migration
