apiVersion: v1
kind: Secret
metadata:
  name: riotx-redis-credentials
  namespace: redis-migration
  labels:
    app.kubernetes.io/name: riotx
    app.kubernetes.io/component: redis-cluster-migration
type: Opaque
stringData:
  source-user: ""
  source-password: "CHANGE_ME_SOURCE_PASSWORD"
  target-user: ""
  target-password: "CHANGE_ME_TARGET_PASSWORD"
